const actionTypes = {
  SET_TRANSFERS: 'SET_TRANSFERS',
  SET_ALL_TRANSFERS: 'SET_ALL_TRANSFERS',
  REMOVE_ALL_TRANSFERS: 'REMOVE_ALL_TRANSFERS',
  SET_LOADING: 'SET_LOADING',
  ADD_TICKETS: 'ADD_TICKETS',
  SET_SORTING: 'SET_SORTING',
  SET_ERROR: 'SET_ERROR'
};

export default actionTypes;